image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - echo "Upload app"
          - zip -r app.zip node_modules bin *.js *.json 
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: AKIAXRTRQOS3JGXVTZRH
              AWS_SECRET_ACCESS_KEY: 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
              AWS_DEFAULT_REGION: us-east-2
              APPLICATION_NAME: 'on-scrap'
              COMMAND: 'upload-only'
              ENVIRONMENT_ID: 'e-ybn4vnrchu'
              ENVIRONMENT_NAME: 'dev1-env'
              ZIP_FILE: "app.zip"
              S3_BUCKET: 'on-scrap-elasticbeanstalk-deployment'
              VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
        artifacts: 
          - app.zip
    - step:
        name: "Deploy to Staging"
        deployment: staging
        script:
        - echo "Deployment!"
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
          variables:
            AWS_ACCESS_KEY_ID: AKIAXRTRQOS3JGXVTZRH
            AWS_SECRET_ACCESS_KEY: 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
            AWS_DEFAULT_REGION: us-east-2
            APPLICATION_NAME: 'on-scrap'
            COMMAND: 'deploy-only'
            VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
            ENVIRONMENT_ID: 'e-ybn4vnrchu'
            ENVIRONMENT_NAME: 'dev1-env'
            ZIP_FILE: "app.zip"
            S3_BUCKET: 'on-scrap-elasticbeanstalk-deployment'
            WAIT: 'true'
